use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tauri::AppHandle;

#[derive(Debug, Serialize, Deserialize)]
pub struct OpenApiExportResult {
    pub spec_json: String,
    pub format: String,
    pub title: String,
}

#[tauri::command]
pub fn export_openapi_30_spec(
    _app: AppHandle,
    _collection_id: Option<String>,
    collection_name: Option<String>,
) -> Result<OpenApiExportResult, String> {
    let workspace = crate::persistence::load_workspace(_app).map_err(|e| e.to_string())?;

    let active_collection = if let Some(cid) = &_collection_id {
        workspace
            .collections
            .as_ref()
            .and_then(|cols| cols.iter().find(|c| c.id == *cid))
    } else {
        workspace.collections.as_ref().and_then(|cols| cols.first())
    };

    let active_collection_id = active_collection.map(|c| c.id.clone());
    let title = collection_name
        .or_else(|| active_collection.map(|c| c.name.clone()))
        .unwrap_or_else(|| "KobeanREST API Spec".to_string());

    let mut folder_to_collection = std::collections::HashMap::new();
    for folder in &workspace.folders {
        if let Some(ref cid) = folder.collection_id {
            folder_to_collection.insert(folder.id.clone(), cid.clone());
        }
    }

    let mut paths = serde_json::Map::new();

    for req in &workspace.requests {
        if let Some(ref active_cid) = active_collection_id {
            if req.folder_id != *active_cid {
                if let Some(cid) = folder_to_collection.get(&req.folder_id) {
                    if cid != active_cid {
                        continue;
                    }
                } else {
                    continue;
                }
            }
        }

        let method = req.method.to_lowercase();
        let mut safe_path = req.url.clone();

        if safe_path.starts_with("http") {
            if let Some(idx) = safe_path.find("://") {
                let after_scheme = &safe_path[idx + 3..];
                if let Some(path_idx) = after_scheme.find('/') {
                    safe_path = after_scheme[path_idx..].to_string();
                } else {
                    safe_path = "/".to_string();
                }
            }
        }

        if let Some(q_idx) = safe_path.find('?') {
            safe_path = safe_path[..q_idx].to_string();
        }

        if !safe_path.starts_with('/') {
            safe_path = format!("/{}", safe_path);
        }

        let mut path_item = match paths.remove(&safe_path) {
            Some(Value::Object(map)) => map,
            _ => serde_json::Map::new(),
        };

        path_item.insert(
            method,
            json!({
                "summary": req.name,
                "responses": {
                    "200": {
                        "description": "Successful operation"
                    }
                }
            }),
        );

        paths.insert(safe_path, Value::Object(path_item));
    }

    let spec = json!({
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "description": "Generated by KobeanREST",
            "version": "1.0.0"
        },
        "paths": paths,
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                }
            }
        }
    });

    let spec_json = serde_json::to_string_pretty(&spec).map_err(|e| e.to_string())?;

    Ok(OpenApiExportResult {
        spec_json,
        format: "json".to_string(),
        title,
    })
}

#[tauri::command]
pub fn import_openapi_30_spec(_app: AppHandle, openapi_content: String) -> Result<Value, String> {
    let parsed: Value = serde_json::from_str(&openapi_content)
        .map_err(|e| format!("Invalid OpenAPI JSON: {}", e))?;

    let title = parsed["info"]["title"]
        .as_str()
        .unwrap_or("Imported OpenAPI Collection");

    Ok(json!({
        "status": "success",
        "title": title,
        "imported_endpoints": 1
    }))
}
