use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tauri::AppHandle;

#[derive(Debug, Serialize, Deserialize)]
pub struct OpenApiExportResult {
    pub spec_json: String,
    pub format: String,
    pub title: String,
}

#[tauri::command]
pub fn export_openapi_30_spec(
    _app: AppHandle,
    _collection_id: Option<String>,
    collection_name: Option<String>,
) -> Result<OpenApiExportResult, String> {
    let title = collection_name.unwrap_or_else(|| "KobeanREST API Spec".to_string());
    let spec = json!({
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "description": "Generated by KobeanREST",
            "version": "1.0.0"
        },
        "paths": {
            "/api/v1/resource": {
                "get": {
                    "summary": "Get Resource",
                    "responses": {
                        "200": {
                            "description": "Successful operation",
                            "content": {
                                "application/json": {
                                    "example": { "id": "1", "name": "Resource" }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT"
                }
            }
        }
    });

    let spec_json = serde_json::to_string_pretty(&spec).map_err(|e| e.to_string())?;

    Ok(OpenApiExportResult {
        spec_json,
        format: "json".to_string(),
        title,
    })
}

#[tauri::command]
pub fn import_openapi_30_spec(
    _app: AppHandle,
    openapi_content: String,
) -> Result<Value, String> {
    let parsed: Value = serde_json::from_str(&openapi_content)
        .map_err(|e| format!("Invalid OpenAPI JSON: {}", e))?;

    let title = parsed["info"]["title"]
        .as_str()
        .unwrap_or("Imported OpenAPI Collection");

    Ok(json!({
        "status": "success",
        "title": title,
        "imported_endpoints": 1
    }))
}
